-- 테이블 및 시퀀스 삭제 (초기화용)
DROP TABLE RESERVATIONS;
DROP TABLE SHOW_SEATS;
DROP TABLE SHOWS;
DROP TABLE MOVIES;
DROP TABLE USERS;
DROP TABLE SEATS;
DROP SEQUENCE SEQ_USERS;
DROP SEQUENCE SEQ_MOVIES;
DROP SEQUENCE SEQ_SHOWS;
DROP SEQUENCE SEQ_SEATS;
DROP SEQUENCE SEQ_SHOW_SEATS;
DROP SEQUENCE SEQ_RESERVATIONS;

-- USERS 테이블
CREATE TABLE USERS (
    USER_ID VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    IS_ADMIN NUMBER(1) DEFAULT 0 NOT NULL -- 0: 일반사용자, 1: 관리자
);

-- MOVIES 테이블
CREATE TABLE MOVIES (
    MOVIE_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    GENRE VARCHAR2(50),
    RUNNING_TIME NUMBER -- 분 단위
);
CREATE SEQUENCE SEQ_MOVIES;

-- SHOWS 테이블
CREATE TABLE SHOWS (
    SHOW_ID NUMBER PRIMARY KEY,
    MOVIE_ID NUMBER NOT NULL,
    SHOW_TIME TIMESTAMP NOT NULL,
    CONSTRAINT FK_SHOWS_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_SHOWS;

-- SEATS 테이블 (A1 ~ C5 좌석 미리 생성)
CREATE TABLE SEATS (
    SEAT_ID NUMBER PRIMARY KEY,
    SEAT_NUMBER VARCHAR2(3) NOT NULL UNIQUE
);
CREATE SEQUENCE SEQ_SEATS;

-- SHOW_SEATS 테이블 (특정 상영의 좌석 상태)
CREATE TABLE SHOW_SEATS (
    SHOW_SEAT_ID NUMBER PRIMARY KEY,
    SHOW_ID NUMBER NOT NULL,
    SEAT_ID NUMBER NOT NULL,
    IS_RESERVED NUMBER(1) DEFAULT 0 NOT NULL, -- 0: 예매가능, 1: 예매불가
    CONSTRAINT FK_SHOW_SEATS_SHOW_ID FOREIGN KEY (SHOW_ID) REFERENCES SHOWS(SHOW_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHOW_SEATS_SEAT_ID FOREIGN KEY (SEAT_ID) REFERENCES SEATS(SEAT_ID) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_SHOW_SEATS;

-- RESERVATIONS 테이블
CREATE TABLE RESERVATIONS (
    RESERVATION_ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL,
    SHOW_ID NUMBER NOT NULL,
    SEAT_ID NUMBER NOT NULL,
    RESERVATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_RES_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RES_SHOW_ID FOREIGN KEY (SHOW_ID) REFERENCES SHOWS(SHOW_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RES_SEAT_ID FOREIGN KEY (SEAT_ID) REFERENCES SEATS(SEAT_ID) ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_RESERVATIONS;

-- 좌석 데이터 삽입 (A1~C5)
BEGIN
    FOR r IN 1..3 LOOP
        FOR c IN 1..5 LOOP
            INSERT INTO SEATS (SEAT_ID, SEAT_NUMBER)
            VALUES (SEQ_SEATS.NEXTVAL, CHR(64+r) || c);
        END LOOP;
    END LOOP;
    COMMIT;
END;
/
